LogFile        /www/htdocs/w005c0bf/ffb_onlinetest/logs/access_log_2010-02-21
OutputDir      /www/htdocs/w005c0bf/ffb_onlinetest/usage
HostName       ffb.tobijat.at
FlagDir        nmm_flags
HideReferrer   ffb.tobijat.at
Incremental    yes
PageType       htm*
PageType       cgi
PageType       pl
PageType       php*
Quiet          yes
ReallyQuiet    yes
HideURL        *.gif
HideURL        *.GIF
HideURL        *.jpg
HideURL        *.JPG
HideURL        *.ra
HideURL        *.png
HideURL        *.PNG
GeoDB          yes
GeoDBDatabase  /usr/share/GeoDB/GeoDB.dat
CountryFlags   yes